#!/usr/bin/env bash

set -e

BINARY="$1"
if [ -z "$BINARY" ] ; then
    echo 'No binary provided to upload'
    exit 1
fi

REPO="$(git config --get remote.origin.url | sed 's/.*://')"

let PATCH=$(sed -r 's/.*\.//' version)+1
VERSION="$(sed -r 's/[0-9]+$//' version)$PATCH"
echo $VERSION > version

echo "Creating new version for $REPO: $VERSION"

echo 'Committing and tagging new version'
ssh -oStrictHostKeyChecking=no git@github.com &>/dev/null || true
git add version
git commit -m "Build version $VERSION" &>/dev/null
git tag -f "v$VERSION" &>/dev/null
git push origin ":v$VERSION" &>/dev/null || true
git push origin "v$VERSION" &>/dev/null

echo 'Push up the new root tarball'
targit -a .github -c -f $REPO v$VERSION $BINARY >/dev/null

echo 'Merge new version into master'
git checkout master &>/dev/null
git merge "v$VERSION" &>/dev/null
git push origin master &>/dev/null

