#!/usr/bin/env bash

docker run \
    --rm -t -i \
    -v $SSH_AUTH_SOCK:/auth.sock \
    -e SSH_AUTH_SOCK=/auth.sock \
    -v $(pwd):/opt/nsinit \
    -v ~/.gitconfig:/root/.gitconfig \
    nsinit $1

